path: .
train: splits/ctg_fold0_train.txt
val: splits/ctg_fold0_train_monitor.txt
names:
  0: auto_rickshaw
  1: bicycle
  2: bus
  3: car
  4: cart_vehicle
  5: construction_vehicle
  6: motorbike
  7: person
  8: priority_vehicle
  9: three_wheeler
  10: truck
